server:
  port: 8081

spring:
  application:
    name: user

  docker:
    compose:
      lifecycle-management: start_and_stop
      enabled: true
      file: /home/developer/java_projects/craftwine/user/docker-compose.yaml


  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgresql
    url: jdbc:postgresql://localhost:5432/user_db
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/