server:
  port: 8761 # ???? ??? Eureka Server

eureka:
  client:
    register-with-eureka: false  # ??? ?????? ?? ?????????????? ? ?????? Eureka ???????
    fetch-registry: false        # ?? ????? ??????????? ?????? ????????
  server:
    enable-self-preservation: false  # ????????? self-preservation ??? ????????? ??????????
